apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: christopher-farhood-org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik-external
  rules:
  - host: christopher.farhood.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  wordpress
            port:
              number: 80
  tls:
  - hosts:
    - christopher.farhood.org
    secretName: farhood-org-cert-letsencrypt-prod
