---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  labels:
    name: dbdata
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests: 
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwdata-christopher.farhood.org
  labels:
    name: wwwdata-christopher.farhood.org
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - soft
  - nfsvers=4.1
  - rsize=32768
  - wsize=32768
  nfs:
    path: /mnt/pool0/sites/christopher-farhood-org
    server: spielberg.farhoodliquor.dmz

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwdata
  labels:
    name: wwwdata
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests: 
      storage: 1Ti
  volumeName: wwwdata-christopher.farhood.org